package generator

import (
	"bytes"
	"fmt"
	"text/template"

	"github.com/huanghe/clash-unchained/internal/config"
	"github.com/huanghe/clash-unchained/internal/domains"
)

type TemplateData struct {
	Residential  ResidentialData
	Options      OptionsData
	ProxyGroup   ProxyGroupData
	AIDomains    []string
}

type ResidentialData struct {
	Name     string
	Server   string
	Port     int
	Username string
	Password string
}

type OptionsData struct {
	TailscaleBypass bool
	Tailnet         string
	FirstHopProxy   string
}

type ProxyGroupData struct {
	Name string
}

func Generate(cfg *config.Config, domainsPath string) (string, error) {
	nodeName := cfg.NodeName
	if nodeName == "" {
		nodeName = "Long-Term-Proxy"
	}

	data := TemplateData{
		Residential: ResidentialData{
			Name:     nodeName,
			Server:   cfg.ResidentialServer,
			Port:     cfg.ResidentialPort,
			Username: cfg.ResidentialUsername,
			Password: cfg.ResidentialPassword,
		},
		Options: OptionsData{
			TailscaleBypass: cfg.TailscaleBypass,
			Tailnet:         cfg.Tailnet,
			FirstHopProxy:   cfg.FirstHopProxy,
		},
		ProxyGroup: ProxyGroupData{
			Name: cfg.ProxyGroupName,
		},
	}

	if cfg.UseBuiltinDomains {
		rules, err := domains.Load(domainsPath)
		if err != nil {
			return "", fmt.Errorf("failed to load AI domains: %w", err)
		}
		data.AIDomains = rules
	}

	if len(cfg.CustomDomains) > 0 {
		data.AIDomains = append(data.AIDomains, cfg.CustomDomains...)
	}

	if len(data.AIDomains) == 0 {
		return "", fmt.Errorf("no AI domains configured")
	}

	proxyGroupName := cfg.ProxyGroupName
	for i := range data.AIDomains {
		data.AIDomains[i] = fmt.Sprintf("DOMAIN-SUFFIX,%s,%s", data.AIDomains[i], proxyGroupName)
	}

	tmpl, err := template.New("injection.js").Parse(injectionJSTemplate)
	if err != nil {
		return "", fmt.Errorf("failed to parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("failed to execute template: %w", err)
	}

	return buf.String(), nil
}

const injectionJSTemplate = `/**
 * Clash Script Injection for AI Service Chain Proxy
 * 
 * This script injects a chain proxy configuration for AI services into Clash subscriptions.
 * Generated by clash-unchained.
 * 
 * Compatible with: Clash Verge 2.4.x / Mihomo 1.19.x
 * 
 * @param {Object} config - Original Clash configuration
 * @returns {Object} Modified Clash configuration
 */
function main(config) {
  // ============ 1. INJECT RESIDENTIAL IP NODE ============
  
  const residentialIP = {
    name: "{{ .Residential.Name }}",
    type: "socks5",
    server: "{{ .Residential.Server }}",
    port: {{ .Residential.Port }},
    username: "{{ .Residential.Username }}",
    password: "{{ .Residential.Password }}",
    "skip-cert-verify": false,
    udp: true,
    "dialer-proxy": "{{ .Options.FirstHopProxy }}"
  };
  
  config.proxies = [...(config.proxies || []), residentialIP];
  
  // ============ 2. INJECT AI PROXY GROUP ============
  
  const aiProxyGroup = {
    name: "{{ .ProxyGroup.Name }}",
    type: "select",
    proxies: ["{{ .Residential.Name }}"]
  };
  
  config["proxy-groups"] = [aiProxyGroup, ...(config["proxy-groups"] || [])];
  
  // ============ 3. INJECT AI SERVICE RULES ============
  
  const aiServiceRules = [
{{ range $i, $rule := .AIDomains }}{{ if $i }},{{ end }}
    "{{ $rule }}"{{ end }}
  ];
{{ if .Options.TailscaleBypass }}
  
  // ============ 4. TAILSCALE BYPASS RULES ============
  
  const tailscaleRules = [
    "IP-CIDR,100.64.0.0/10,DIRECT,no-resolve",
    "IP-CIDR6,fd7a:115c:a1e0::/64,DIRECT,no-resolve",
    "DOMAIN-SUFFIX,ts.net,DIRECT",
    "DOMAIN,hhport.{{ .Options.Tailnet }},DIRECT",
    "DOMAIN,huang-thinkpad-a475.{{ .Options.Tailnet }},DIRECT",
    "DOMAIN,iphone-12-pro.{{ .Options.Tailnet }},DIRECT",
    "DOMAIN-SUFFIX,{{ .Options.Tailnet }},DIRECT"
  ];
  
  if (!config.dns) {
    config.dns = {};
  }
  config.dns.enable = true;
  config.dns["enhanced-mode"] = "fake-ip";
  
  // fake-ip-filter: + prefix means exclude from fake-ip
  const tsNetDomains = [
    "+ts.net",
    "+{{ .Options.Tailnet }}"
  ];
  config.dns["fake-ip-filter"] = [
    ...tsNetDomains,
    ...(config.dns["fake-ip-filter"] || [])
  ];
  
  // Global nameserver: put Tailscale DNS first
  const tailscaleDns = "100.100.100.100";
  config.dns.nameserver = [tailscaleDns, ...(config.dns.nameserver || [])];
  
  // nameserver-policy: domain-specific DNS strategy
  config.dns["nameserver-policy"] = {
    "ts.net": [tailscaleDns],
    "{{ .Options.Tailnet }}": [tailscaleDns],
    ...(config.dns["nameserver-policy"] || {})
  };
  
  config.rules = [...tailscaleRules, ...aiServiceRules, ...(config.rules || [])];
{{ else }}
  config.rules = [...aiServiceRules, ...(config.rules || [])];
{{ end }}
  
  return config;
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { main };
}
`
